version: 2
project_name: epusdt

builds:
  - main: ./main.go          # ← 位于 src/main.go，相对 workdir=./src
    goos:   [linux, windows, darwin]
    goarch: [amd64, arm64]
    ldflags: ["-s -w"]

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - ./static/**          # 把 src/static/** 打包进归档

changelog:
  use: github

release: {}   # 直接用缺省行为，GoReleaser 会自动解析 origin URL
